import Vue from "vue";
import {
  Toast,
  Dialog,
  Cell,
  CellGroup,
  ActionSheet,
  NumberKeyboard,
  Area,
  Popup,
  Field,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Button,
  Panel,
  Step,
  Steps,
  Tag,
  List,
  Loading,
  DatetimePicker
} from "vant";
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(ActionSheet);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(NumberKeyboard);
Vue.use(Area);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Button);
Vue.use(Panel);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Tag);
Vue.use(List);
Vue.use(Loading);
Vue.use(DatetimePicker);